<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.23.osoe-925" />

  <PropertyGroup>
    <Title>Lombiq API Client for Orchard Core</Title>
    <CopyrightYear>2022</CopyrightYear>
    <DescriptionBody>A client library for communicating with the Orchard Core web APIs.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;Refit;OpenId;ApiClient</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Core-API-Client</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Core-API-Client</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.3.3" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="OrchardCore.ContentManagement.Abstractions" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true' and Exists($(LombiqHelpfulLibrariesPath))">
    <ProjectReference Include="$(LombiqHelpfulLibrariesPath)\Lombiq.HelpfulLibraries.Refit\Lombiq.HelpfulLibraries.Refit.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true' and !Exists($(LombiqHelpfulLibrariesPath))">
    <ProjectReference Include="..\..\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.Refit\Lombiq.HelpfulLibraries.Refit.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.Refit" Version="12.6.1-alpha.10.osoe-925" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Library.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.Library.Sdk" Version="1.0.1-alpha.23.osoe-925" />
</Project>
